behaviors:
  Turret:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1280
      learning_rate: 3.0e-3
      beta: 0.005
      epsilon: 0.2
      lambd: 0.97
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 3
    checkpoint_interval: 200000
    max_steps: 2000000
    time_horizon: 128
    time_horizon: 64
    summary_freq: 10000
    threaded: true